version: '2'

services:
  syntax:
    build: syntax

  editorconfig:
    build: editorconfig

  rubocop:
    build: rubocop
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  shellcheck:
    build: shellcheck
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  eslint:
    build: eslint
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  gometalinter:
    build: gometalinter
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  phpcs:
    build: phpcs
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  api:
    build: test/fake_api
    ports:
      - "9292:9292"
