version: '2'

services:
  syntax:
    build: syntax

  rubocop:
    build: rubocop
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  shellcheck:
    build: shellcheck
    environment:
      TEAMCI_REPO_SLUG: ~
      TEAMCI_COMMIT: ~

  api:
    build: test/fake_api
    ports:
      - "9292:9292"
