version: '2'

services:
  syntax:
    build: syntax

  rubocop:
    build: rubocop

  shellcheck:
    image: koalaman/shellcheck:v0.4.7

  api:
    build: test/fake_api
    ports:
      - "9292:9292"
