steps:
  - label: syntax
    command: script/syntax

  - label: rubocop
    command: script/rubocop

  - label: shellcheck
    command: script/shellcheck

  - label: editorconfig
    command: script/editorconfig

  - label: eslint
    command: script/eslint
